/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liautardclotilde.projettreillis;

import static liautardclotilde.projettreillis.Classes.Calcul.Resolution;
import static liautardclotilde.projettreillis.Classes.Calcul.creeMatrice;
import liautardclotilde.projettreillis.Classes.Matrice;
import static liautardclotilde.projettreillis.Classes.Matrice.resolutionGauss;
import static liautardclotilde.projettreillis.Classes.Matrice.test4;
import static liautardclotilde.projettreillis.Projet_Treillis.test;

/**
 *
 * @author Elève
 */
public class AfficheTension extends Projet_Treillis {

    /**
     * Creates new form AfficheTension
     */
    public AfficheTension() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nom = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Afficher les Tensions");

        jButton1.setText("Afficher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Afficherun(evt);
            }
        });

        jButton2.setText("Afficher");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2AfficherTout(evt);
            }
        });

        jLabel1.setText("Afficher la résistance d'une Barre");

        jLabel2.setText("Afficher la résistance de toutes les Barres");

        jButton3.setText("Fermer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3Fermer(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Broadway", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Votre Treillis va-t-il tenir face aux forces de ");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Broadway", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("compression et/ou de tension ??");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Afficherun(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Afficherun
        // TODO add your handling code here:
        int Nom = ((Integer)nom.getValue());
        //création de la matrice etc
        try{
        int nbNoeud=getlisteNoeuds().size();
        int nc =getlisteBarre().size();
        Matrice c =new Matrice(2*getlisteNoeuds().size(),getlisteBarre().size()+2*getlisteAD().size()+getlisteAS().size());
        c.creeVecteur(2*getlisteNoeuds().size());
      
        double force =1000;
        for(int j=0;j<2*getlisteNoeuds().size()-1;j++)
        {
            //if (getlisteNoeuds().get(j).getClass()==Noeud_Simple.class){
               //c.set(j,0,force); 
           //}else{
                c.set(j,0,0);
           // }
        }
        Matrice v = new Matrice (2*getlisteNoeuds().size(),2*getlisteNoeuds().size());
        

        //fin de créaction matrice etc, on va chercher notre valeur
        
        for (int i=0;i<getlisteBarre().size();i++){
                
            v.set(i,0,resolutionGauss(creeMatrice(),c).get(i,0));                    
        }
        
        test4(creeMatrice(),c,2*getlisteNoeuds().size(),2*getlisteNoeuds().size());
        
                
        resolutionGauss(creeMatrice(),c).toString();                    
        Resolution();
        for (int i=0;i<getlisteBarre().size();i++){
            if(getlisteBarre().get(i).getnom()==Nom){
                if (v.get(i,0)>getlisteBarre().get(i).gettype().getRcmax()){
                    new Erreur17().setVisible(true);
                    dispose();
                    //message d'erreur
                } 
                if (v.get(i,0)>getlisteBarre().get(i).gettype().getRtmax()){
                    new Erreur17().setVisible(true);
                    dispose();
                    //message d'erreur
                } else{
                    
                    new Erreur18().setVisible(true);
                    dispose();

                }
            }
        }
        }catch (Exception e) {  
        }
        //test();
    }//GEN-LAST:event_Afficherun

    private void jButton2AfficherTout(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2AfficherTout
        // TODO add your handling code here:
        int nbNoeud=getlisteNoeuds().size();
        int nc =getlisteBarre().size();
        int compte=0;
        try{
        Matrice c =new Matrice(2*getlisteNoeuds().size(),getlisteBarre().size()+2*getlisteAD().size()+getlisteAS().size());
        c.creeVecteur(2*getlisteNoeuds().size());
      
        double force =1000;
        for(int j=0;j<2*getlisteNoeuds().size()-1;j++)
        {
            //if (listeNoeuds.get(j).getClass()==Noeud_Simple.class){
              // c.set(j,0,force); 
           //}else{
                c.set(j,0,0);
            //}
        }
        Matrice v = new Matrice (2*getlisteNoeuds().size(),2*getlisteNoeuds().size());
        

        //fin de créaction matrice etc, on va chercher notre valeur
        
        for (int i=0;i<getlisteBarre().size();i++){
                
            v.set(i,0,resolutionGauss(creeMatrice(),c).get(i,0));
                            
        }
        for (int i=0;i<getlisteBarre().size();i++){
            
            if (v.get(i,0)>getlisteBarre().get(i).gettype().getRcmax()){                
                compte=compte+1;
                //message d'erreur
            } 
            if (v.get(i,0)>getlisteBarre().get(i).gettype().getRtmax()){                
                compte=compte+1;
                //à vérifier si ça prend bien Rtmax dans la matrice
            } 
            
        }
        //si une des tensions est trop élevée
        if (compte>0){            
           new Erreur17().setVisible(true);
           dispose();
           
        } else {            
            new Erreur18().setVisible(true);
            dispose();
        }
        
        }catch (Exception e) {  
        }
    }//GEN-LAST:event_jButton2AfficherTout

    private void jButton3Fermer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3Fermer
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3Fermer
                    //for toute la liste
                    //et pour une barre en particulier
                    ////if barre.get(i).gettype.tension
                    //if en compression et un en tension
                    //si R>Rmax alors message la barre s'écroule
                    //sinon tout va bien
                    //comme message d'erreur
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AfficheTension.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AfficheTension.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AfficheTension.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AfficheTension.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AfficheTension().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner nom;
    // End of variables declaration//GEN-END:variables
}
