/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liautardclotilde.projettreillis;

import java.util.Arrays;
import liautardclotilde.projettreillis.Classes.PointTerrain;
import liautardclotilde.projettreillis.Classes.TriangleTerrain;
import static liautardclotilde.projettreillis.Edit1.getId1;
import static liautardclotilde.projettreillis.NewTriangleTerrain.VerifTT;

/**
 *
 * @author Elève
 */
public class EditTriangleTerrain extends Projet_Treillis {

    /**
     * Creates new form EditTriangleTerrain
     */
    public EditTriangleTerrain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        Abs1 = new javax.swing.JTextField();
        Ord1 = new javax.swing.JTextField();
        Abs2 = new javax.swing.JTextField();
        Ord2 = new javax.swing.JTextField();
        Abs3 = new javax.swing.JTextField();
        Ord3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Annuler = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Point 3:");

        jLabel1.setText("Abscisse");

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Annuler(evt);
            }
        });

        jLabel2.setText("Ordonne");

        jButton2.setText("Terminer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Terminer(evt);
            }
        });

        jLabel3.setText("Point 1:");

        jLabel4.setText("Point 2:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(8, 8, 8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ord1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Abs1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Abs2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ord2))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Abs3)
                            .addComponent(Ord3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Annuler)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addGap(0, 59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Abs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Abs2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Abs3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Ord1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ord2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ord3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Annuler)
                    .addComponent(jButton2))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Annuler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Annuler
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_Annuler

    private void Terminer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Terminer
        // TODO add your handling code here:
        int u=0;
        try{
            double x1=Double.parseDouble(Abs1.getText());
            //System.out.println(x1);
            double x2=Double.parseDouble(Abs2.getText());
            //System.out.println(x2);
            double x3=Double.parseDouble(Abs3.getText());
            //System.out.println(x3);
            double y1=Double.parseDouble(Ord1.getText());
            //System.out.println(y1);
            double y2=Double.parseDouble(Ord2.getText());
            //System.out.println(y2);
            double y3=Double.parseDouble(Ord3.getText());
            //System.out.println(y3);
            PointTerrain PT1=new PointTerrain (x1,y1,0);
            //System.out.println(PT1.getNom()+":("+PT1.getPx()+","+PT1.getPy()+")");
            PointTerrain PT2=new PointTerrain (x2,y2,1);
           // System.out.println(PT2.getNom()+":("+PT2.getPx()+","+PT2.getPy()+")");
            PointTerrain PT3=new PointTerrain (x3,y3,2);
            //System.out.println(PT3.getNom()+":("+PT3.getPx()+","+PT3.getPy()+")");
            if ((PT1.Verification_Appartenance_TerrainP(getT())==true)&&(PT2.Verification_Appartenance_TerrainP(getT())==true)&&(PT3.Verification_Appartenance_TerrainP(getT())==true)){
                for (int i=0;i<getlisteTT().size();i++){
                    u=u+1;
                    if (getId1()==getlisteTT().get(i).getNOM()){
                        u=u+1;
                        TriangleTerrain TT= new TriangleTerrain (PT1,PT2,PT3,getlisteTT().get(i).getNOM());
                        //System.out.println(listeTT.get(i).toString());
                        if (TT.verifUniciteTroisPoints()==false){
                            new Erreur8().setVisible(true);
                        }else{
                            if (VerifTT(getlisteTT(),TT)==false){ 
                                new Erreur5().setVisible(true);
                            }else{
                                getlisteTT().get(i).setpT1(PT1);
                                getlisteTT().get(i).setpT2(PT2);
                                getlisteTT().get(i).setpT3(PT3);    
                                System.out.println(Arrays.toString(getlisteTT().toArray()));
                                dispose();
                            }
                        }
                    }
                }
            }else{
                new Erreur6().setVisible(true);
            } 
        }catch (NumberFormatException e) {
            if (u==0){
                System.out.println("CATCH1");
                new Erreur2().setVisible(true); 
            }
             if (u==1){
                 System.out.println("CATCH2");
                new Erreur8().setVisible(true); 
            }
            if (u==2){
                System.out.println("CATCH3");
                new Erreur5().setVisible(true); 
            }
        }
    }//GEN-LAST:event_Terminer

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTriangleTerrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTriangleTerrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTriangleTerrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTriangleTerrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditTriangleTerrain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Abs1;
    private javax.swing.JTextField Abs2;
    private javax.swing.JTextField Abs3;
    private javax.swing.JButton Annuler;
    private javax.swing.JTextField Ord1;
    private javax.swing.JTextField Ord2;
    private javax.swing.JTextField Ord3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
