/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liautardclotilde.projettreillis;

import java.util.Arrays;
import liautardclotilde.projettreillis.Classes.PointTerrain;
import liautardclotilde.projettreillis.Classes.Noeuds;
import liautardclotilde.projettreillis.Classes.Noeud_Simple;
import liautardclotilde.projettreillis.Classes.Appui_Double;
import liautardclotilde.projettreillis.Classes.Appui_Simple;
import liautardclotilde.projettreillis.Classes.Noeud_Appui;
import static liautardclotilde.projettreillis.Edit2.getId2;
import static liautardclotilde.projettreillis.NewNoeuds.VerifListeNoeudsAppui;

/**
 *
 * @author Elève
 */
public class EditNoeudAppui extends Projet_Treillis {

    /**
     * Creates new form EditNoeudAppui
     */
    public EditNoeudAppui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        type = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        P2 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        alpha = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        TriangleT = new javax.swing.JSpinner();
        jButton4 = new javax.swing.JButton();
        P1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Appui_Double", "Appui_Simple" }));

        jLabel2.setText("- Point 1 (P1):");

        jLabel3.setText("- Point 2 (P2):");

        jLabel4.setText("Position sur le Segment P1/P2 (alpha): ");

        jLabel5.setText("Point du Triangle Terrain:");

        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Annuler(evt);
            }
        });

        jButton3.setText("Terminer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Terminer(evt);
            }
        });

        jButton4.setText("Modifier un Noeud (Simple)");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditNoeud(evt);
            }
        });

        jLabel6.setText("Type:");

        jLabel1.setText("Triangle Terrain:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TriangleT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(P2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(alpha)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TriangleT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(P2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(alpha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Annuler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Annuler
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_Annuler

    private void Terminer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Terminer
        // TODO add your handling code here:
        int u=0;//Variable pour Catch
        try{
            int nomTT = ((Integer)TriangleT.getValue());
            int nomPt1 = ((Integer)P1.getValue());
            int nomPt2 = ((Integer)P2.getValue());
            String typeNoeud=type.getSelectedItem().toString();
            double al=Double.parseDouble(alpha.getText());
            System.out.println("TT:"+nomTT+", nom PT1:"+nomPt1+", nom PT2:"+nomPt1+", alpha:"+al);
            
            PointTerrain P1=new PointTerrain(0,0,0);
            PointTerrain P2=new PointTerrain(0,0,0);
            u=u+1;
            if ((0<=nomPt1&&nomPt1<3)||(0<=nomPt2&&nomPt2<3)){
                for (int i=0;i<getlisteTT().size();i++){
                    if (getlisteTT().get(i).getNOM()==nomTT){
                        if (getlisteTT().get(i).getPT1().getNom()==nomPt1){
                            P1=getlisteTT().get(i).getPT1();
                        }
                        if (getlisteTT().get(i).getPT2().getNom()==nomPt1){
                            P1=getlisteTT().get(i).getPT2();
                        }
                        if (getlisteTT().get(i).getPT3().getNom()==nomPt1){
                            P1=getlisteTT().get(i).getPT3();
                        }
                    
                        if (getlisteTT().get(i).getPT1().getNom()==nomPt2){
                            P2=getlisteTT().get(i).getPT1();
                        }
                        if (getlisteTT().get(i).getPT2().getNom()==nomPt2){
                            P2=getlisteTT().get(i).getPT2();
                        }
                        if (getlisteTT().get(i).getPT3().getNom()==nomPt2){
                            P2=getlisteTT().get(i).getPT3();
                        }
                            if (P1==P2){
                                new Erreur8().setVisible(true); 
                            }else{
                                u=u+1;
                                Noeuds noeud=new Noeud_Appui(getlisteNoeuds().size()+1,getlisteTT().get(i),P1,P2,al); 
                                if (noeud.Verification_Appartenance_TerrainN(getT())==true){
                                    u=u+1;
                                    if ("Appui_Double".equals(typeNoeud)){
                                        noeud=new Appui_Double(getlisteTT().get(i),P1,P2,al,getlisteNoeuds().size()+1);
                                        System.out.println(noeud.toString());
                                        if (VerifListeNoeudsAppui(getlisteNoeuds(),noeud)==true){
                                            for (int j=0;j<getlisteNoeuds().size();j++){
                                                if (getId2()==getlisteNoeuds().get(j).getnom()){
                                                    noeud=new Appui_Double(getlisteTT().get(i),P1,P2,al,getlisteNoeuds().get(j).getnom());
                                                    System.out.println();
                                                    System.out.println(getlisteNoeuds().get(j));
                                                    System.out.println(Arrays.toString(getlisteNoeuds().toArray()));
                                                    getlisteNoeuds().set(j,noeud);
                                                    if (getlisteNoeuds().get(j).getClass()==Appui_Double.class){ 
                                                        dispose(); 
                                                    }
                                                    if (getlisteNoeuds().get(j).getClass()==Appui_Simple.class){ 
                                                        getlisteAS().remove(getlisteNoeuds().get(j));
                                                        getlisteAD().add(getlisteNoeuds().get(j));
                                                        dispose(); 
                                                    }
                                                    if (getlisteNoeuds().get(j).getClass()==Noeud_Simple.class){ 
                                                        getlisteNS().remove(getlisteNoeuds().get(j));
                                                        getlisteAD().add(getlisteNoeuds().get(j));
                                                        dispose(); 
                                                    }
                                                }
                                            }
                                        }else{
                                            new Erreur6().setVisible(true); 
                                        }
                                    }
                                    u=u+1;
                                    if ("Appui_Simple".equals(typeNoeud)){
                                        noeud=new Appui_Simple(getlisteTT().get(i),P1,P2,al,getlisteNoeuds().size()+1);
                                        System.out.println(noeud.toString());
                                        if (VerifListeNoeudsAppui(getlisteNoeuds(),noeud)==true){
                                            for (int j=0;j<getlisteNoeuds().size();j++){
                                                if (getId2()==getlisteNoeuds().get(j).getnom()){
                                                    noeud=new Appui_Simple(getlisteTT().get(i),P1,P2,al,getlisteNoeuds().get(j).getnom());
                                                    System.out.println();
                                                    System.out.println(getlisteNoeuds().get(j));
                                                    System.out.println(Arrays.toString(getlisteNoeuds().toArray()));
                                                    getlisteNoeuds().set(j,noeud);
                                                    if (getlisteNoeuds().get(j).getClass()==Appui_Double.class){
                                                        getlisteAD().remove(getlisteNoeuds().get(j));
                                                        getlisteAS().add(getlisteNoeuds().get(j));
                                                        dispose(); 
                                                    }
                                                    if (getlisteNoeuds().get(j).getClass()==Appui_Simple.class){ 
                                                        dispose(); 
                                                    }
                                                    if (getlisteNoeuds().get(j).getClass()==Noeud_Simple.class){ 
                                                        getlisteNS().remove(getlisteNoeuds().get(j));
                                                        getlisteAS().add(getlisteNoeuds().get(j));
                                                        dispose(); 
                                                    }
                                                }
                                            }
                                        }else{
                                            new Erreur6().setVisible(true); 
                                        }    
                                    }
                                }else{
                                    new Erreur6().setVisible(true); 
                                }
                            }
                    }else{
                        new Erreur10().setVisible(true);//Nouvelle erreur ????     
                    }
                }
            }else{
                new Erreur15().setVisible(true); 
            }
        }catch (NumberFormatException e) {
            if (u==0){
                System.out.println("CATCH1");
                new Erreur2().setVisible(true); 
            }
            if (u==1){
                System.out.println("CATCH2: problème appartenance Terrain");
            }
            if (u==2){
                System.out.println("CATCH3: problème type Appui Double"); 
            }
            if (u==3){
                System.out.println("CATCH3: problème type Appui Simple"); 
            }
            if (u==4){
                System.out.println("CATCH4: "); 
            }
	}
    }//GEN-LAST:event_Terminer

    private void EditNoeud(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditNoeud
        // TODO add your handling code here:
        new EditNoeudSimple().setVisible(true);
        dispose();
    }//GEN-LAST:event_EditNoeud

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditNoeudAppui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditNoeudAppui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditNoeudAppui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditNoeudAppui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditNoeudAppui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner P1;
    private javax.swing.JSpinner P2;
    private javax.swing.JSpinner TriangleT;
    private javax.swing.JTextField alpha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
